# Generated by Django 5.2.6 on 2025-09-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_order_options_alter_product_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
