# Generated by Django 5.2.6 on 2025-09-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_product_category_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
