# Generated by Django 5.2.6 on 2025-09-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_order_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Mã thuốc'),
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn'),
        ),
        migrations.AddField(
            model_name='product',
            name='import_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Giá nhập'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Giá bán'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nhà cung cấp'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Viên', 'Viên'), ('Hộp', 'Hộp'), ('Chai', 'Chai'), ('Ống', 'Ống'), ('Gói', 'Gói')], max_length=20, null=True, verbose_name='Đơn vị'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Thuốc kê đơn', 'Thuốc kê đơn'), ('Thuốc không kê đơn', 'Thuốc không kê đơn'), ('Thực phẩm chức năng', 'Thực phẩm chức năng'), ('Dụng cụ y tế', 'Dụng cụ y tế')], max_length=50, null=True, verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Tên thuốc'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='Số lượng'),
        ),
    ]
