# Generated by Django 5.2.6 on 2025-09-13 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_product_code_product_expiry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(null=True, verbose_name='Số lượng')),
                ('is_collected', models.BooleanField(default=False, verbose_name='Đã lấy thuốc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hoàn tất')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bác sĩ')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product', verbose_name='Tên thuốc')),
            ],
            options={
                'verbose_name_plural': 'Prescription',
            },
        ),
    ]
