# Generated by Django 5.2.6 on 2025-09-13 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(null=True, verbose_name='Số lượng')),
                ('is_collected', models.BooleanField(default=False, verbose_name='Đã lấy thuốc')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='dashboard.prescription', verbose_name='Toa thuốc')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product', verbose_name='Tên thuốc')),
            ],
            options={
                'verbose_name_plural': 'Prescription Details',
            },
        ),
    ]
