# Generated by Django 5.2.6 on 2025-09-16 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_prescriptiondetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='is_collected',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='product',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='quantity',
        ),
    ]
