# Generated by Django 5.2.6 on 2025-09-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_prescription_is_collected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='import_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Giá nhập'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Giá bán'),
        ),
    ]
