# Generated by Django 5.2.6 on 2025-09-25 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_patient_prescription_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.prescription', verbose_name='Từ toa thuốc'),
        ),
    ]
