# Generated by Django 5.2.6 on 2025-09-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_order_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('Pending', 'Chờ lấy thuốc'), ('Dispensed', 'Đã lấy thuốc'), ('Cancelled', 'Đã hủy')], default='Pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
