# Generated by Django 5.2.6 on 2025-10-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_patient_allergies_patient_blood_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.AddField(
            model_name='patient',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='patient_avatars/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='patient',
            name='citizen_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Số CCCD'),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AddField(
            model_name='patient',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dân tộc'),
        ),
        migrations.AddField(
            model_name='patient',
            name='health_insurance_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Số BHYT'),
        ),
    ]
